name: 'upload'
description: 'Upload a file to a server'

inputs:
  id:
    description: 'ID of the resume to build'
    required: true

outputs:
  data:
    description: 'temp output'

runs:
  using: node20
  main: dist/index.js