name: Build Latex to PDF

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID of the resume to build'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
        actions-directoy: [ 'apps/actions' ]
        actions: [ 'latex', 'pdf' ]
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - run: pnpm build
        working-directory: join(${{ matrix.actions-directory }}, ${{ matrix.actions }})

#      - id: action
#        uses: ./${{ matrix.directory }}/latex
#        with:
#          id: ${{ github.event.inputs.id }}
#
#      - run: echo "${{ steps.action.outputs.data }}"