name: Build Latex to PDF

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID of the resume to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
        actions-directory: [ 'apps/actions' ]
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - run: pnpm build
        working-directory: ${{ matrix.actions-directory }}/latex

      - uses: ./apps/actions/latex
        id: latex
        with:
          id: ${{ github.event.inputs.id }}

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ steps.latex.outputs.path }}

      - run: pnpm build
        working-directory: ${{ matrix.actions-directory }}/upload
        env:
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
        with:
          id: ${{ github.event.inputs.id }}
          latex_path: ${{ steps.latex.outputs.path }}
