name: Build Latex to PDF

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID of the resume to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: leplusorg/latex:latest
    strategy:
      matrix:
        node-version: [20]
        actions-directory: ['apps/actions']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Corepack
        run: npm install -g corepack

      - run: corepack enable

      - uses: pnpm/action-setup@v4

      - run: pnpm install && pnpm build
        working-directory: ${{ matrix.actions-directory }}

      - uses: ./apps/actions
        with:
          id: '1'